# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Y', models.DecimalField(decimal_places=10, max_digits=19)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
